// Top SoC: RISC-V CV32E40X core + ECG coprocessor + memory-mapped peripherals +
// two memories. First module connecting all three components in the project.
//
// WHY IT PREVIOUSLY DID NOT EXIST, and why that matters. Measured:
//
//   * `ecg_coproc` was never instantiated in a parent module -- always top-module of TB/synth.
//   * `grep -c "ecg_soc\|soc_top\|ecg_top"` across codebase = 0.
//   * Comment in ecg_core_xif.sv deferred coproc connection to top level.
//   * 80-firmware/ contained only README + five .gitkeep files.
//
// Earlier area/power/freq figures represented standalone blocks rather than integrated system.
// Valid per-block measurements, but system execution was previously unproven.
// This module closes that gap.
//
// ADDRESS MAP (designed for single small bitfield decode, see `sel_*` below):
//
//   0x0000_0000 .. 0x0000_1FFF   IMEM  8 KB   read-only from instruction bus
//   0x0001_0000 .. 0x0001_1FFF   DMEM  8 KB   read/write from data bus
//   0x2000_0000 .. 0x2000_1FFF   MMIO  8 KB   ecg_mmio
//
// Core BOOT_ADDR is 0x0000_0080 (ecg_core_xif.sv), so program starts at IMEM word 32.
//
// CONTROL SOURCES. Coprocessor receives `start/single/layer/dma_start/dma_len` from
// ONE of TWO sources, selected via `ctrl_sel` (CTRL bit 6 of MMIO):
//
//   ctrl_sel = 0 (DEFAULT): from CUSTOM INSTRUCTIONS via CV-X-IF.
//     Primary thesis path -- ISA extension rather than memory-mapped peripheral.
//   ctrl_sel = 1: from MMIO. Exists for a SPECIFIC reason: `ecg_cvxif` hardwires
//     `cp_single_o = 1'b1`, preventing firmware from invoking autonomous multi-layer mode
//     (single = 0: execute layer 0 to layer with 'last' flag) via instructions.
//     Autonomous mode is fastest path through model, tested in `make sim-coproc`.
//
// MEMORIES. In simulation implemented as `logic` arrays; `$readmemh` loads IMEM from
// hex generated by `objcopy -O verilog --verilog-data-width=4`. Caveats identified:
//   1. Without `--verilog-data-width=4` objcopy outputs bytes, misread as 32-bit words.
//   2. Final section word may lack bytes, resolved by `. = ALIGN(4);` in linker script.
//   3. `$readmemh` does not error on missing file; guarded at BOOT_ADDR below.
//
//
//
//
//
//
//
//
//
//
//
//
//
module ecg_soc
  import ecg_pkg::*;
#(
    parameter int unsigned IMEM_WORDS = 2048,          // 8 KB
    // DMEM 16 KB, not 8: model image of m1-cnn is 6,632 B (9 descriptors + 4,572 B
    // weights + 106 scales + 105 biases + 256 inputs) coexisting in DMEM
    // with signature area and stack. 8 KB is insufficient.
    // DMEM 48 KB: FOUR model images (26,752 B) + signature area + stack. All four families
    // co-resident in memory allows firmware real MODEL SWITCHING -- central claim
    // of paper, previously demonstrated only at block level.
    parameter int unsigned DMEM_WORDS = 12288,         // 48 KB
    parameter        string IMEM_HEX  = "",            // hex file for $readmemh
    // DMEM_HEX loads MODEL IMAGE (descriptors + weights + tables + inputs) into DMEM.
    // Standard SoC behavior: non-volatile memory image loaded into peripheral by CPU.
    // Generated by tools/gen_model_hex.py with '@' directive placing data at word 1024.
    //
    parameter        string DMEM_HEX  = "",
    parameter int unsigned WFIFO_DEPTH = 8,
    // HOST-06. Previously constant 868, calculated for 100 MHz. Fixed SoC clock is
    // 41,666,667 Hz (T = 24 ns), yielding ~48,000 baud instead of 115,200 (2.4x off).
    //
    //
    // Divisor is DERIVED from parameters and rounded to nearest integer.
    //
    //
    //
    parameter int unsigned CLK_HZ    = 41_666_667,
    parameter int unsigned UART_BAUD = 115_200,
    // Default is EXPRESSION, not number. Simulation can override with small value
    // (`-GUART_CK_MOI_BIT=8`) -- full speed simulation takes 868 cycles/bit, too slow for CI.
    //
    //
    parameter int unsigned UART_CK_MOI_BIT = (CLK_HZ + UART_BAUD / 2) / UART_BAUD,
    parameter int unsigned ABITS = $clog2(ECG_ACT_BYTES),
    parameter int unsigned WBITS = $clog2(ECG_WMEM_BYTES)
) (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        fetch_enable_i,

    // External visibility for testbench and board bring-up.
    output logic        core_sleep_o,
    output logic        cp_busy_o,
    output logic        cp_done_o,
    output logic        xif_kill_seen_o,
    output logic [63:0] mcycle_o,

    // DMEM DEBUG read port. Exists for two reasons:
    //   1. System testbench reads signature words written by firmware without VPI.
    //   2. Board bring-up reads DMEM words without JTAG.
    // Read-only, combinational, first 32 words of DMEM. No state side-effects.
    //
    //
    //
    //
    //
    // 8-bit address covers 256 words; .sig section reserves 128 words.
    //
    //
    //
    //
    //
    //
    //
    //
    input  logic [7:0]  dbg_addr_i,
    output logic [31:0] dbg_data_o,

    // PC and valid flag from core debug port. Distinguishes three failure modes:
    // instruction fetch hang (PC at BOOT_ADDR), trap handler loop (PC at _trap),
    // or handshake hang (PC inside main loop).
    //
    //
    output logic        dbg_pc_valid_o,
    output logic [31:0] dbg_pc_o,
    output logic [31:0] dbg_instr_addr_o,

    // ---- APB4 slave port: ingress for EXTERNAL MASTER ---------------------
    // Zynq PS via AXI-APB bridge, second core, or debugger. NOT on local CPU path:
    // placing APB between CPU and registers adds latency (OBI 1-2 cycles, APB min 2-3).
    //
    //
    //
    // Connects verified `ecg_apb_slave` block into SoC interconnect.
    //
    input  logic        apb_psel_i,
    input  logic        apb_penable_i,
    input  logic        apb_pwrite_i,
    input  logic [31:0] apb_paddr_i,
    input  logic [31:0] apb_pwdata_i,
    input  logic [3:0]  apb_pstrb_i,
    output logic [31:0] apb_prdata_o,
    output logic        apb_pready_o,
    output logic        apb_pslverr_o,

    // ---- UART pins: input from host PC or sensor ---------------------------
    input  logic        uart_rx_i,
    output logic        uart_tx_o
);

  // ---- INSTRUCTION bus --------------------------------------------------
  // i_addr[1:0] unused: CV32E40X word-aligned fetch, lower two bits always 0.
  /* verilator lint_off UNUSEDSIGNAL */
  logic [31:0] i_addr;
  /* verilator lint_on UNUSEDSIGNAL */
  logic        i_req, i_gnt, i_rvalid, i_err;
  logic [31:0] i_rdata;

  // ---- DATA bus ---------------------------------------------------------
  logic        d_req, d_gnt, d_rvalid, d_we, d_err, d_exokay;
  logic [31:0] d_addr, d_wdata, d_rdata;
  logic [3:0]  d_be;

  // ---- Coprocessor control, dual source ---------------------------------
  logic        xif_start, xif_single, xif_dma_start;
  logic [5:0]  xif_layer;
  logic [13:0] xif_dma_len;

  logic        mm_ctrl_sel, mm_start, mm_single, mm_dma_start;
  logic [5:0]  mm_layer, mm_n_layers;
  logic [9:0]  mm_in_len;
  logic [WBITS:0] mm_dma_len;

  logic        cp_start, cp_single, cp_dma_start;
  logic [5:0]  cp_layer;
  logic [WBITS:0] cp_dma_len;

  assign cp_start     = mm_ctrl_sel ? mm_start     : xif_start;
  assign cp_single    = mm_ctrl_sel ? mm_single    : xif_single;
  assign cp_layer     = mm_ctrl_sel ? mm_layer     : xif_layer;
  assign cp_dma_start = mm_ctrl_sel ? mm_dma_start : xif_dma_start;
  // xif_dma_len is 14 bits wide; WBITS = $clog2(4664) = 13 so dma_len is 14 bits.
  assign cp_dma_len   = mm_ctrl_sel ? mm_dma_len   : xif_dma_len[WBITS:0];

  // ---- EXEC-04: latch configuration per RUN -----------------------------
  // Three fields below are read by `ecg_coproc` AFTER start cycle, so host writes
  // mid-run would corrupt active execution. See header in ecg_cfg_shadow.sv.
  // ITEM EXEC-06: shadow registers form configuration epoch latched at START.
  //
  //
  logic       cfg_single;
  logic [5:0] cfg_n_layers;
  logic [9:0] cfg_in_len;

  ecg_cfg_shadow #(.W(1)) u_cfg_single (
      .clk_i, .rst_ni, .start_i(cp_start), .live_i(cp_single), .held_o(cfg_single)
  );
  ecg_cfg_shadow #(.W(6)) u_cfg_n_layers (
      .clk_i, .rst_ni, .start_i(cp_start), .live_i(mm_n_layers), .held_o(cfg_n_layers)
  );
  ecg_cfg_shadow #(.W(10)) u_cfg_in_len (
      .clk_i, .rst_ni, .start_i(cp_start), .live_i(mm_in_len), .held_o(cfg_in_len)
  );

  // ---- MMIO to coprocessor interface ------------------------------------
  logic cp_desc_illegal;
  logic        cp_busy, cp_done;
  logic        desc_req; logic [5:0] desc_idx;
  logic        desc_valid; logic [ECG_DESC_BYTES*8-1:0] desc_word;
  logic [13:0] s_off; logic [9:0] b_off;
  logic [ECG_REQUANT_MULT_BITS-1:0]  s_mult;
  logic [ECG_REQUANT_SHIFT_BITS-1:0] s_shift;
  logic signed [8:0] s_bias;
  logic        dma_busy, dma_done, ws_valid, ws_ready;
  logic [63:0] ws_data;
  logic        pre_we; logic [3:0] pre_buf; logic [ABITS-1:0] pre_off;
  logic signed [7:0] pre_data;
  logic        wr_v; logic [3:0] wr_buf; logic [ABITS-1:0] wr_off;
  logic signed [7:0] wr_data; logic wr_last;

  assign cp_busy_o = cp_busy;
  assign cp_done_o = cp_done;

  // ---- CORE + CV-X-IF bridge + shim -------------------------------------
  ecg_core_xif u_core (
      .clk_i, .rst_ni, .fetch_enable_i,
      .core_sleep_o,
      .instr_req_o     (i_req),
      .instr_gnt_i     (i_gnt),
      .instr_rvalid_i  (i_rvalid),
      .instr_addr_o    (i_addr),
      .instr_memtype_o (),
      .instr_prot_o    (),
      .instr_dbg_o     (),
      .instr_rdata_i   (i_rdata),
      .instr_err_i     (i_err),
      .data_req_o      (d_req),
      .data_gnt_i      (d_gnt),
      .data_rvalid_i   (d_rvalid),
      .data_addr_o     (d_addr),
      .data_be_o       (d_be),
      .data_we_o       (d_we),
      .data_wdata_o    (d_wdata),
      .data_memtype_o  (),
      .data_prot_o     (),
      .data_dbg_o      (),
      .data_atop_o     (),
      .data_rdata_i    (d_rdata),
      .data_err_i      (d_err),
      .data_exokay_i   (d_exokay),
      .irq_i           (32'b0),
      .time_i          (64'b0),
      .mcycle_o,
      .debug_havereset_o (),
      .debug_running_o   (),
      .debug_halted_o    (),
      .debug_pc_valid_o  (dbg_pc_valid_o),
      .debug_pc_o        (dbg_pc_o),
      .cp_start_o      (xif_start),
      .cp_single_o     (xif_single),
      .cp_layer_o      (xif_layer),
      .cp_busy_i       (cp_busy),
      .cp_done_i       (cp_done),
      .dma_start_o     (xif_dma_start),
      .dma_len_o       (xif_dma_len),
      .dma_busy_i      (dma_busy),
      .xif_kill_seen_o
  );

  // ---- COPROCESSOR ------------------------------------------------------
  ecg_coproc u_cp (
      .clk_i, .rst_ni,
      .start_i     (cp_start),
      .single_i    (cfg_single),
      .layer_i     (cp_layer),
      .n_layers_i  (cfg_n_layers),
      .in_len_i    (cfg_in_len),
      .busy_o      (cp_busy),
      .done_o      (cp_done),
      .desc_req_o  (desc_req),
      .desc_idx_o  (desc_idx),
      .desc_valid_i(desc_valid),
      .desc_word_i (desc_word),
      .s_off_o     (s_off),
      .b_off_o     (b_off),
      .s_mult_i    (s_mult),
      .s_shift_i   (s_shift),
      .s_bias_i    (s_bias),
      .dma_start_i (cp_dma_start),
      .dma_len_i   (cp_dma_len),
      .dma_busy_o  (dma_busy),
      .dma_done_o  (dma_done),
      .ws_valid_i  (ws_valid),
      .ws_data_i   (ws_data),
      .ws_ready_o  (ws_ready),
      .pre_we_i    (pre_we),
      .pre_buf_i   (pre_buf),
      .pre_off_i   (pre_off),
      .pre_data_i  (pre_data),
      .wr_o        (wr_v),
      .wr_buf_o    (wr_buf),
      .wr_off_o    (wr_off),
      .wr_data_o   (wr_data),
      .wr_last_layer_o (wr_last),
      .desc_illegal_o    (cp_desc_illegal)
  );

  // ---- DATA bus address decode ------------------------------------------
  // Decode MMIO at 0x2000_0000 and DMEM at 0x0001_0000.
  // Narrow decode is intentional: any address outside these windows is a firmware
  // error and must raise bus error rather than reading undefined garbage.
  //
  logic sel_mmio, sel_dmem, sel_invalid;
  assign sel_mmio    = (d_addr[31:28] == 4'h2);
  assign sel_dmem    = (d_addr[31:16] == 16'h0001);
  assign sel_invalid = d_req && !sel_mmio && !sel_dmem;

  // ---- MMIO -------------------------------------------------------------
  logic        mm_req, mm_rvalid;
  logic [31:0] mm_rdata;
  assign mm_req = d_req && sel_mmio;

  // ---- UART: instantiated here rather than in ecg_mmio ------------------
  // Register block is window for firmware, not container for peripherals.
  // Instantiated at SoC level to route `rx_i`/`tx_o` to top-level pins.
  //
  logic [7:0] u_rx_data, u_tx_data;
  logic       u_rx_valid, u_rx_frame_err, u_tx_valid, u_tx_ready;

  ecg_uart #(.CK_MOI_BIT(UART_CK_MOI_BIT)) u_uart (
      .clk_i, .rst_ni,
      .rx_i           (uart_rx_i),
      .tx_o           (uart_tx_o),
      .rx_data_o      (u_rx_data),
      .rx_valid_o     (u_rx_valid),
      .rx_frame_err_o (u_rx_frame_err),
      .tx_data_i      (u_tx_data),
      .tx_valid_i     (u_tx_valid),
      .tx_ready_o     (u_tx_ready)
  );

  // ---- APB -> OBI -> arbiter -> ecg_mmio --------------------------------
  logic        apb_req, apb_gnt, apb_we, apb_rvalid;
  logic [31:0] apb_addr, apb_wdata, apb_rdata;
  logic [3:0]  apb_be;

  ecg_apb_slave #(.ABITS(32)) u_apb (
      .clk_i, .rst_ni,
      .psel_i    (apb_psel_i),
      .penable_i (apb_penable_i),
      .pwrite_i  (apb_pwrite_i),
      .paddr_i   (apb_paddr_i),
      .pwdata_i  (apb_pwdata_i),
      .pstrb_i   (apb_pstrb_i),
      .prdata_o  (apb_prdata_o),
      .pready_o  (apb_pready_o),
      .pslverr_o (apb_pslverr_o),
      .req_o     (apb_req),
      .gnt_i     (apb_gnt),
      .addr_o    (apb_addr),
      .we_o      (apb_we),
      .be_o      (apb_be),
      .wdata_o   (apb_wdata),
      .rvalid_i  (apb_rvalid),
      .rdata_i   (apb_rdata)
  );

  logic        mux_req, mux_gnt, mux_we, mux_rvalid;
  logic [31:0] mux_addr, mux_wdata, mux_rdata;
  logic [3:0]  mux_be;
  logic        cpu_gnt, cpu_rvalid;
  logic [31:0] cpu_rdata;

  // CPU PRIORITY: APB access takes 2-3 cycles while OBI takes 1 cycle.
  // Giving APB priority would stall CPU cycle budget (measured in 90-results).
  //
  //
  ecg_mmio_mux u_mux (
      .clk_i, .rst_ni,
      .a_req_i (mm_req),    .a_gnt_o (cpu_gnt),
      .a_addr_i(d_addr),    .a_we_i  (d_we),
      .a_be_i  (d_be),      .a_wdata_i(d_wdata),
      .a_rvalid_o(cpu_rvalid), .a_rdata_o(cpu_rdata),
      .b_req_i (apb_req),   .b_gnt_o (apb_gnt),
      .b_addr_i(apb_addr),  .b_we_i  (apb_we),
      .b_be_i  (apb_be),    .b_wdata_i(apb_wdata),
      .b_rvalid_o(apb_rvalid), .b_rdata_o(apb_rdata),
      .s_req_o (mux_req),   .s_gnt_i (mux_gnt),
      .s_addr_o(mux_addr),  .s_we_o  (mux_we),
      .s_be_o  (mux_be),    .s_wdata_o(mux_wdata),
      .s_rvalid_i(mux_rvalid), .s_rdata_i(mux_rdata)
  );

  assign mm_rvalid = cpu_rvalid;
  assign mm_rdata  = cpu_rdata;

  // WFIFO_DEPTH parameter enables determinism testing: deep FIFO decoupling CPU
  // isolates backpressure interactions.
  ecg_mmio #(.ABITS(ABITS), .WBITS(WBITS), .WFIFO_DEPTH(WFIFO_DEPTH)) u_mmio (
      .clk_i, .rst_ni,
      .req_i    (mux_req),
      .gnt_o    (mux_gnt),
      .addr_i   (mux_addr),
      .we_i     (mux_we),
      .be_i     (mux_be),
      .wdata_i  (mux_wdata),
      .rvalid_o (mux_rvalid),
      .rdata_o  (mux_rdata),
      .u_rx_data_i      (u_rx_data),
      .u_rx_valid_i     (u_rx_valid),
      .u_rx_frame_err_i (u_rx_frame_err),
      .u_tx_data_o      (u_tx_data),
      .u_tx_valid_o     (u_tx_valid),
      .u_tx_ready_i     (u_tx_ready),
      .ctrl_sel_o    (mm_ctrl_sel),
      .cp_start_o    (mm_start),
      .cp_single_o   (mm_single),
      .cp_layer_o    (mm_layer),
      .cp_n_layers_o (mm_n_layers),
      .cp_in_len_o   (mm_in_len),
      .cp_desc_illegal_i (cp_desc_illegal),
      .cp_busy_i     (cp_busy),
      .cp_done_i     (cp_done),
      .desc_req_i    (desc_req),
      .desc_idx_i    (desc_idx),
      .desc_valid_o  (desc_valid),
      .desc_word_o   (desc_word),
      .s_off_i       (s_off),
      .b_off_i       (b_off),
      .s_mult_o      (s_mult),
      .s_shift_o     (s_shift),
      .s_bias_o      (s_bias),
      .dma_start_o   (mm_dma_start),
      .dma_len_o     (mm_dma_len),
      .dma_busy_i    (dma_busy),
      .dma_done_i    (dma_done),
      .ws_valid_o    (ws_valid),
      .ws_data_o     (ws_data),
      .ws_ready_i    (ws_ready),
      .pre_we_o      (pre_we),
      .pre_buf_o     (pre_buf),
      .pre_off_o     (pre_off),
      .pre_data_o    (pre_data),
      .wr_i          (wr_v),
      .wr_buf_i      (wr_buf),
      .wr_off_i      (wr_off),
      .wr_data_i     (wr_data),
      .wr_last_layer_i (wr_last)
  );

  // ---- IMEM -------------------------------------------------------------
  // Indices must be truncated to exact array width. Upper bits decode region
  // in `sel_*`; including them in index causes silent aliasing on invalid access.
  //
  //
  localparam int unsigned IAW = $clog2(IMEM_WORDS);
  localparam int unsigned DAW = $clog2(DMEM_WORDS);
  logic [31:0] imem [IMEM_WORDS];
  logic [IAW-1:0] i_idx;
  logic [DAW-1:0] d_idx;
  assign i_idx = i_addr[IAW+1:2];
  assign d_idx = d_addr[DAW+1:2];
  logic [31:0] im_rdata_q;
  logic        im_rvalid_q, im_err_q;

  assign i_gnt    = 1'b1;
  assign i_rvalid = im_rvalid_q;
  assign i_rdata  = im_rdata_q;
  // `err` belongs to RESPONSE phase, not REQUEST phase. In OBI, `err` accompanies
  // `rvalid` rather than `req`, breaking combinational loop.
  //
  //
  //
  //
  assign i_err    = im_err_q;

  // W2-BOOT-2 / V1-C FENCE 1: ARRAY OUTSIDE ASYNC RESET PROCESS.
  //
  // Placing memories in async reset process prevents block RAM inference
  // (Xilinx BRAM has no async array reset), forcing Vivado error 8-3391.
  // Memory contents are initialized by $readmemh or written by CPU.
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  // Partitioned into memory data path (no reset) and control registers
  // (async reset). Control registers determine data validity via rvalid.
  //
  //
  always_ff @(posedge clk_i) begin
    if (i_req && (i_addr[31:2] < 30'(IMEM_WORDS)))
      im_rdata_q <= imem[i_idx];
    else
      im_rdata_q <= 32'h0;
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      im_rvalid_q <= 1'b0;
      im_err_q    <= 1'b0;
    end else begin
      im_rvalid_q <= i_req;
      im_err_q    <= i_req && (i_addr[31:2] >= 30'(IMEM_WORDS));
    end
  end

  // ---- DMEM -------------------------------------------------------------
  logic [31:0] dmem [DMEM_WORDS];
  logic [31:0] dm_rdata_q;
  logic        dm_rvalid_q;
  logic        d_err_q;

  // BRAM Port A: CPU read and write. Mutually exclusive in `if (d_we)`
  // sharing one port without async reset.
  //
  always_ff @(posedge clk_i) begin
    if (d_req && sel_dmem) begin
      if (d_we) begin
        // Byte-enable writes: partial writes (sb/sh) update addressed bytes only.
        // Verified to infer 16 RAMB36 blocks.
        //
        //
        //
        if (d_be[0]) dmem[d_idx][7:0]   <= d_wdata[7:0];
        if (d_be[1]) dmem[d_idx][15:8]  <= d_wdata[15:8];
        if (d_be[2]) dmem[d_idx][23:16] <= d_wdata[23:16];
        if (d_be[3]) dmem[d_idx][31:24] <= d_wdata[31:24];
      end else begin
        dm_rdata_q <= dmem[d_idx];
      end
    end
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      dm_rvalid_q <= 1'b0;
      d_err_q     <= 1'b0;
    end else begin
      // rvalid for BOTH read and write: OBI expects response for every accepted
      // transaction including writes; core stalls on first sw without it.
      dm_rvalid_q <= d_req && sel_dmem;
      d_err_q     <= sel_invalid;
    end
  end

  assign dbg_instr_addr_o = i_addr;

  // DEBUG READ PORT: SYNCHRONOUS BRAM Port B (V1-C Fence 1).
  //
  // Port B dedicated to debug read without interfering with CPU Port A.
  // Uses true dual-port BRAM inference with 1-cycle latency.
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  logic [31:0] dbg_data_q;
  // BRAM Port B: synchronous debug read.
  //
  //
  //
  //
  //
  always_ff @(posedge clk_i) begin
    dbg_data_q <= dmem[{{(DAW-8){1'b0}}, dbg_addr_i}];
  end
  assign dbg_data_o = dbg_data_q;

  // ---- Data bus response ------------------------------------------------
  assign d_gnt    = 1'b1;
  // Even invalid addresses must respond to avoid bus hang.
  //
  assign d_rvalid = mm_rvalid || dm_rvalid_q || d_err_q;
  assign d_rdata  = mm_rvalid ? mm_rdata : dm_rdata_q;
  // Error flag belongs to response phase; registered one cycle after request.
  //
  assign d_err    = d_err_q;
  assign d_exokay = 1'b1;

  // ---- Program loading + assertions -------------------------------------
`ifndef SYNTHESIS
  /* verilator coverage_off */
  // Verification state wrapped in coverage_off to prevent toggling artifacts.
  //
  //
  //
  // --------------------------------------------------------------- W1-A F01
  // Bridge scoreboard: tracks accepted, killed, and responded transactions.
  //
  //
  //
  //
  // Invariant: recv - killed - resp == outstanding.
  //
  //
  //
  //
  //
  //
  // F11: killed instruction leaves no pending response in CV-X-IF.
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  // ITEM XIF-05: scoreboard assertion recv - killed - resp == outstanding.
  always_ff @(posedge clk_i) begin
    if (rst_ni && ((u_core.u_bridge.f_n_recv_q - u_core.u_bridge.f_n_killed_q
                    - u_core.u_bridge.f_n_resp_q)
                   != {31'b0, u_core.u_bridge.id_pend_valid_q}))
      $error("ecg_soc: [W1-A] scoreboard cau lech -- nhan %0d, huy %0d, tra %0d, outstanding %0d",
             u_core.u_bridge.f_n_recv_q, u_core.u_bridge.f_n_killed_q,
             u_core.u_bridge.f_n_resp_q, u_core.u_bridge.id_pend_valid_q);
  end

  // ---------------------------------------------------------------- F03 item 3
  // PRE-DEADLOCK INVARIANT. 1-deep LOADW queue in ecg_cvxif stalls 3rd command
  // when full. Stalling issue port is safe only if loader does not depend on CPU.
  //
  //
  //
  //
  //
  // Pre-deadlock condition: LOADW stalled at issue & loader busy & words pending & WFIFO empty.
  //
  //
  //
  //
  //
  //
  logic f_loadw_stalled, f_bytes_pending, f_wfifo_empty, f_pre_deadlock;
  assign f_loadw_stalled = u_core.u_cvxif.iss_valid_i && u_core.u_cvxif.is_loadw
                        && !u_core.u_cvxif.iss_ready_o;
  assign f_bytes_pending = u_cp.u_wm.busy_q
                        && (u_cp.u_wm.wr_word_q < u_cp.u_wm.wr_words_q);
  assign f_wfifo_empty   = u_mmio.wf_empty;
  assign f_pre_deadlock  = f_loadw_stalled && f_bytes_pending && f_wfifo_empty;

  // Distance tracking to deadlock condition: monitor cycles where loader awaits CPU data.
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  logic [31:0] f_n_stalled_q, f_n_wait_cpu_q, f_n_pre_deadlock_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      f_n_stalled_q      <= '0;
      f_n_wait_cpu_q     <= '0;
      f_n_pre_deadlock_q <= '0;
    end else begin
      if (f_loadw_stalled)                  f_n_stalled_q      <= f_n_stalled_q + 1;
      if (f_bytes_pending && f_wfifo_empty) f_n_wait_cpu_q     <= f_n_wait_cpu_q + 1;
      if (f_pre_deadlock)                   f_n_pre_deadlock_q <= f_n_pre_deadlock_q + 1;
      if (f_pre_deadlock)
        $error("ecg_soc: [F03] TIEN KHOA CHET -- LOADW bi chan o cong issue, bo nap con no byte, WFIFO RONG: chi CPU moi cap duoc ma CPU dang bi chan");
    end
  end

  final begin
    $display("ecg_soc: [F03] LOADW stalled %0d ck · loader waiting CPU %0d ck · pre-deadlock %0d ck",
             f_n_stalled_q, f_n_wait_cpu_q, f_n_pre_deadlock_q);
    if (f_n_stalled_q == 0)
      $display("ecg_soc: [F03] NOTE -- 0 cycles LOADW stalled; pre-deadlock invariant trivially holds this run");
  end

  /* verilator coverage_on */
`endif

  // ---- MEMORY INITIALIZATION: MUST run during synthesis (V1-C Fence 2) ----
  //
  // Initial block outside SYNTHESIS guard allows tool to infer BRAM init.
  //
  //
  //
  //
  //
  //
  //
  //
  // $readmemh in initial block is standard practice for BRAM initialization.
  //
  //
  // Fatal assertions guarded by ifndef SYNTHESIS to check file existence in simulation.
  //
  //
  //
  //
  //
  //
  //
  //
  initial begin
    if (DMEM_HEX != "") begin
      $readmemh(DMEM_HEX, dmem);
      // Model image must start with magic "MDIR" at 0x0001_1000 (word 1024).
      // Early verification ensures valid descriptors before simulation proceeds.
      //
      //
      //
`ifndef SYNTHESIS
      if (dmem[1024] !== 32'h4D444952) begin
        $display("ecg_soc: ERROR -- manifest at 0x11000 magic %h, expected 4D444952 (MDIR)",
                 dmem[1024]);
        $display("  DMEM_HEX = %s", DMEM_HEX);
        $display("  Run `python3 tools/gen_model_hex.py` and retry.");
        $fatal(1, "ecg_soc: anh mo hinh khong nap duoc");
      end
`endif
    end
    if (IMEM_HEX != "") begin
      $readmemh(IMEM_HEX, imem);
`ifndef SYNTHESIS
      if (imem[32] === 32'h0 || imem[32] === 'x) begin
        $display("ecg_soc: ERROR -- BOOT_ADDR 0x80 (imem[32]) word is %h.", imem[32]);
        $display("  IMEM_HEX = %s", IMEM_HEX);
        $display("  Potential causes in order of likelihood:");
        $display("   1. objcopy missing --verilog-data-width=4 (outputted bytes)");
        $display("   2. linker script missing `. = ALIGN(4);` at section end");
        $display("   3. program entry not placed at 0x80 (core BOOT_ADDR)");
        $fatal(1, "ecg_soc: IMEM khong nap duoc");
      end
`endif
    end
  end

endmodule
