// Requantisation stage: int32 partial sum -> int8 activation.
//
// This is the module where N2 (bit-exact against the golden vectors) is won or
// lost. The reference is the integer path built in P4
// (tools/compile_model.py), which itself was checked round-trip against
// 30-model/golden/. Any disagreement here shows up one layer later as "the
// model is wrong", where the cause is hardest to find, so the arithmetic is
// spelled out rather than left to inference.
//
// The operation, per output channel c (ADR-0014 §2.3):
//
//     t = round_half_up( psum * mult[c] / 2^shift[c] ) + bias_out[c]
// NUM-01: arithmetic domain locked here and measured via
// `make sim-requant` over 24,860 vectors generated by an independent Python
// reference model (`tools/rtl_ref/requant_ref.py`, importing only argparse/random/pathlib).
// Measured on vector file: expected min=-127 max=127, zero vectors expect -128
// (matching assertion below); 4,518 vectors hit -127 and 8,988 hit +127,
// psum covers full +/-8,388,607 range with both ReLU modes tested.
// Key decisions -- allow -128, saturate vs wrap, bias before/after requant --
// are documented below and exercised by test vectors.
// ORACLE-03 validated here: rounding edges, shift, clamp, negative values covered.
//     y = clamp( t, relu ? 0 : -127, 127 )
//
//   * The bias is added AFTER the shift, in the output domain, not before the
//     multiply. Measured over 562 channels: in the psum domain the bias needs
//     16 bits (|max| = 18,728) and breaks the 24 kB N7 budget; in the output
//     domain it needs 8 (|max| = 80) and fits with 232 B to spare.
//   * mult is 11 bits unsigned and shift 5 bits (ecg_pkg), chosen in P4 because
//     4 B per scale would have broken the 1.0 kB descriptor budget.
//   * Rounding is half-up, implemented by adding 2^(shift-1) before the shift.
//     Truncating instead costs about half an LSB of bias per layer, which
//     accumulates across 34 requant sites.
//   * The clamp is symmetric at +/-127, not -128..127: the weight quantiser is
//     symmetric with no zero point, so -128 is never produced and allowing it
//     would make the hardware representable set wider than the model's.
//   * ReLU clamps after the bias add, because the float model computes
//     relu(conv + bias) and not relu(conv) + bias.

`ifndef ECG_REQUANT_SV
`define ECG_REQUANT_SV

module ecg_requant
  import ecg_pkg::*;
(
    input  logic                                clk_i,
    input  logic                                rst_ni,

    input  logic                                valid_i,
    input  logic signed [ECG_PSUM_BITS-1:0]     psum_i,
    // 9 bits, not 8. ADR-0014 §2.3 assumed output domain bias fits int8, but one
    // of 562 entries disproved this: channel 3 of m3.blocks_1_dw_0 has
    // bias = -170; in 8 bits it wrapped to +86, saturating to +127
    // instead of correct 0. Discovered when running full model inference:
    // reference used int64 so succeeded, while per-module testbenches generated
    // bias in [-40, 40] missing the overflow.
    input  logic signed [8:0]                   bias_i,   // output domain
    input  logic [ECG_REQUANT_MULT_BITS-1:0]    mult_i,
    input  logic [ECG_REQUANT_SHIFT_BITS-1:0]   shift_i,
    input  ecg_act_e                            act_i,

    output logic                                valid_o,
    output logic signed [7:0]                   act_o
);

  // psum is ECG_PSUM_BITS and mult is 11, so the product needs 35; one more bit
  // of headroom keeps the rounding add and the bias add from ever wrapping.
  localparam int PROD_W = ECG_PSUM_BITS + ECG_REQUANT_MULT_BITS + 1;   // 36

  logic signed [PROD_W-1:0] prod;
  logic signed [PROD_W-1:0] rounded;
  logic signed [PROD_W-1:0] shifted;
  logic signed [PROD_W-1:0] biased;
  logic signed [7:0]        clamped;

  always_comb begin
    prod = $signed({1'b0, mult_i}) * PROD_W'($signed(psum_i));

    // Parenthesised: `<<<` binds looser than `+`, so without them this would
    // compute (prod + 1) << (shift-1) and break bit-exactness.
    if (shift_i == '0) rounded = prod;
    else               rounded = prod + (PROD_W'(1) <<< (shift_i - 1));

    shifted = rounded >>> shift_i;

    // Bias in the output domain, added here. Widened to PROD_W first so a large
    // shifted value plus a bias cannot wrap before the clamp sees it.
    biased = shifted + PROD_W'($signed(bias_i));

    // Symmetric clamp, and the ReLU lower bound folded into it.
    if      (biased > PROD_W'(127))  clamped = 8'sd127;
    else if (act_i == ECG_ACT_RELU)  clamped = biased[PROD_W-1] ? 8'sd0 : 8'(biased);
    else if (biased < PROD_W'(-127)) clamped = -8'sd127;
    else                             clamped = 8'(biased);
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      valid_o <= 1'b0;
      act_o   <= '0;
    end else begin
      valid_o <= valid_i;
      act_o   <= clamped;
    end
  end

`ifdef FORMAL
  // Proof across ALL inputs, not only 24,860 test vectors.
  //
  // Input state space is 2^49 (psum 24 + mult 11 + shift 5 + bias 9), so exhaustive
  // simulation is intractable and test vectors only confirm tested points.
  // 
  //
  // Written using immediate assertions inside clocked process rather than
  // `assert property`: Yosys `read_slang` rejects concurrent SVA or `$past`;
  // this form runs robustly in the current toolchain.
  // Initial state constraint: formal tool starts from arbitrary register states;
  // without this constraint, properties fire falsely on step 1 due to uninitialized
  // f_v_q vs valid_o mismatch. Holding reset on cycle 0 resolves this.
  // 
  logic f_started_q = 1'b0;
  always_ff @(posedge clk_i) f_started_q <= 1'b1;
  always_comb if (!f_started_q) assume (!rst_ni);

  logic     f_v_q;
  ecg_act_e f_act_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      f_v_q   <= 1'b0;
      f_act_q <= ECG_ACT_NONE;
    end else begin
      f_v_q   <= valid_i;
      f_act_q <= act_i;
    end
  end

  always_ff @(posedge clk_i) begin
    if (rst_ni && f_started_q) begin
      // 1. Output ALWAYS in symmetric int8 range [-127, 127], never -128:
      //    downstream integer path assumes symmetric range; -128 causes silent
      //    one-quantum shift in next layer.
      assert (!valid_o || (act_o >= -8'sd127 && act_o <= 8'sd127));

      // 2. Under ReLU, output is never negative -- even with negative bias and psum.
      //    `act_i` is used combinationally in datapath, so registered value `f_act_q` checked.
      assert (!(valid_o && (f_act_q == ECG_ACT_RELU)) || (act_o >= 8'sd0));

      // 3. Requant stage does not drop or spuriously generate results.
      assert (valid_o == f_v_q);
    end
  end
`endif

endmodule

`endif  // ECG_REQUANT_SV
